#include "gkz_ndim/gkz_ndim.hpp"
#include <cstdlib>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <string>

namespace {
struct Args { std::optional<std::filesystem::path> points, polytope, output; std::int64_t k=0; std::size_t max_points=1000000; bool ell=false; sgkz::SolverOptions options; };
void usage(std::ostream& o){o<<"Usage:\n  sgkz --points FILE [options]\n  sgkz --polytope FILE --k INTEGER [options]\n\nOptions:\n  --output FILE            Write dynamic-column CSV.\n  --ell                    Compute and output affine ell_A.\n  --max-points N           Lattice-point limit (default 1000000; 0 unlimited).\n  --tolerance VALUE        Relative Frank--Wolfe tolerance.\n  --absolute-tolerance V   Absolute gap tolerance.\n  --correction-tolerance V Active-set correction tolerance.\n  --prune-tolerance V     Active coefficient pruning tolerance.\n  --max-iterations N       Maximum active-set expansion steps.\n  --max-correction-steps N Maximum active-set correction steps.\n  --exact-max-active N     Exact QP active-set limit; 0 means unlimited.\n  --no-exact               Skip exact certification.\n  --verbose                Print iteration diagnostics.\n  --help                   Show this message.\n";}
std::string value(int argc,char**argv,int&i,const std::string&o){if(i+1>=argc)throw std::invalid_argument("missing value after "+o);return argv[++i];}
Args parse(int argc,char**argv){Args a;for(int i=1;i<argc;++i){std::string o=argv[i];if(o=="--help"){usage(std::cout);std::exit(0);}else if(o=="--points")a.points=value(argc,argv,i,o);else if(o=="--polytope")a.polytope=value(argc,argv,i,o);else if(o=="--k")a.k=std::stoll(value(argc,argv,i,o));else if(o=="--output")a.output=value(argc,argv,i,o);else if(o=="--ell")a.ell=true;else if(o=="--max-points")a.max_points=std::stoull(value(argc,argv,i,o));else if(o=="--tolerance")a.options.tolerance=std::stod(value(argc,argv,i,o));else if(o=="--absolute-tolerance")a.options.absolute_tolerance=std::stod(value(argc,argv,i,o));else if(o=="--correction-tolerance")a.options.correction_tolerance=std::stod(value(argc,argv,i,o));else if(o=="--prune-tolerance")a.options.prune_tolerance=std::stod(value(argc,argv,i,o));else if(o=="--max-iterations")a.options.max_iterations=std::stoi(value(argc,argv,i,o));else if(o=="--max-correction-steps")a.options.max_correction_steps=std::stoi(value(argc,argv,i,o));else if(o=="--exact-max-active")a.options.exact_max_active=std::stoi(value(argc,argv,i,o));else if(o=="--no-exact")a.options.exact_certification=false;else if(o=="--verbose")a.options.verbose=true;else throw std::invalid_argument("unknown option: "+o);}if(a.points.has_value()==a.polytope.has_value())throw std::invalid_argument("specify exactly one of --points and --polytope");if(a.polytope&&a.k<=0)throw std::invalid_argument("--polytope requires positive --k");if(a.options.max_iterations<0||a.options.max_correction_steps<0||a.options.exact_max_active<0||a.options.tolerance<0||a.options.absolute_tolerance<0||a.options.correction_tolerance<0||a.options.prune_tolerance<0)throw std::invalid_argument("invalid solver option");return a;}
}
int main(int argc,char**argv){try{auto a=parse(argc,argv);auto c=a.points?sgkz::PointConfiguration::from_points_file(*a.points):sgkz::PointConfiguration::from_polytope_file(*a.polytope,a.k,a.max_points);sgkz::ShortestGkzSolver solver(a.options);auto r=solver.solve(c);std::cout<<std::setprecision(17)<<"dimension="<<c.dimension()<<'\n'<<"points="<<c.size()<<'\n'<<"volume="<<sgkz::rational_string(c.volume())<<'\n'<<"converged="<<std::boolalpha<<r.converged<<'\n'<<"iterations="<<r.iterations<<'\n'<<"active_size="<<r.active_vectors.size()<<'\n'<<"norm_squared="<<r.norm_squared<<'\n'<<"gap="<<r.gap<<'\n'<<"l2_error_bound="<<r.l2_error_bound<<'\n'<<"exact_certified="<<r.exact.certified<<'\n';if(r.exact.certified)std::cout<<"exact_norm_squared="<<sgkz::rational_string(r.exact.norm_squared)<<'\n';if(a.ell){auto e=sgkz::compute_ell(c);std::cout<<"ell_A=";for(std::size_t i=0;i<e.exact_coefficients.size();++i){if(i)std::cout<<',';std::cout<<sgkz::rational_string(e.exact_coefficients[i]);}std::cout<<'\n';}if(a.output){sgkz::write_result_csv(*a.output,c,r,a.ell);std::cout<<"output="<<a.output->string()<<'\n';}return r.converged||r.exact.certified?0:2;}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<'\n';return 1;}}
